// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailableAdapters() {
  return window['go']['main']['App']['AvailableAdapters']();
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CompileRevision(arg1, arg2) {
  return window['go']['main']['App']['CompileRevision'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateRevision(arg1, arg2) {
  return window['go']['main']['App']['CreateRevision'](arg1, arg2);
}

export function DefaultWorkspaceDirectory() {
  return window['go']['main']['App']['DefaultWorkspaceDirectory']();
}

export function EvaluateSchedule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EvaluateSchedule'](arg1, arg2, arg3, arg4);
}

export function ExecuteCard(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteCard'](arg1, arg2, arg3, arg4, arg5);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function InterruptTerminal(arg1) {
  return window['go']['main']['App']['InterruptTerminal'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListRevisions(arg1) {
  return window['go']['main']['App']['ListRevisions'](arg1);
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SelectWorkspaceDirectory() {
  return window['go']['main']['App']['SelectWorkspaceDirectory']();
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3);
}

export function TerminalEvents(arg1) {
  return window['go']['main']['App']['TerminalEvents'](arg1);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalInput'](arg1, arg2);
}
