// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agentadapter} from '../models';
import {productgraph} from '../models';
import {execution} from '../models';
import {terminal} from '../models';

export function AvailableAdapters():Promise<Array<agentadapter.Manifest>>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CompileRevision(arg1:string,arg2:string):Promise<productgraph.CompiledPlan>;

export function CreateProject(arg1:string,arg2:string):Promise<productgraph.Project>;

export function CreateRevision(arg1:string,arg2:string):Promise<productgraph.Revision>;

export function DefaultWorkspaceDirectory():Promise<string>;

export function EvaluateSchedule(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<productgraph.ScheduleResult>;

export function ExecuteCard(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<execution.RunResult>;

export function Health():Promise<Record<string, string>>;

export function InterruptTerminal(arg1:string):Promise<void>;

export function ListProjects():Promise<Array<productgraph.Project>>;

export function ListRevisions(arg1:string):Promise<Array<productgraph.Revision>>;

export function ListTerminals():Promise<Array<terminal.Info>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SelectWorkspaceDirectory():Promise<string>;

export function StartTerminal(arg1:string,arg2:Array<string>,arg3:string):Promise<terminal.Info>;

export function TerminalEvents(arg1:string):Promise<Array<terminal.Event>>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
